### ISSUE TITLE
django-simple-history plugin doesn't work correctly with django 1.10 admin UI

### ISSUE THREAD

**Issue by leonmaks** [treyhunner/django-simple-history#237]
When django-simple-history was added to replace default admin UI in django 1.10 the following exception was raised: Exception Value: render() got an unexpected keyword argument 'dictionary' 

Please use the following link for details: http://stackoverflow.com/questions/39179559/django-simple-history-plugin-render-got-an-unexpected-keyword-argument-dictihttp://stackoverflow.com/questions/39179559/django-simple-history-plugin-render-got-an-unexpected-keyword-argument-dicti

**Comment by leonmaks** [comment]
I've corrected this issue by replacing 2 calls of **render** function in simple-history.admin module:
1:
```
78        return render(request, template_name=self.object_history_template,
79                      context=context)

```2:
```
181        return render(request, template_name=self.object_history_form_template,
182                      context=context)
```

**Comment by macro1** [comment]
django-simple-history isn't compatible with 1.10 yet. I have a branch in progress, but work isn't complete.

**Comment by akhayyat** [comment]
What other incompatibilities with Django 1.10 are there, besides the admin integration and the middleware settings?

**Comment by macro1** [comment]
There's also a change in the way management commands are defined, we may be dropping 1.6 support due to that. But it's not too bad over-all, I just haven't had time to work on it yet.

Here is what I have in progress right now: https://github.com/treyhunner/django-simple-history/compare/django110

**Comment by KevinGrahamFoster** [comment]
Hey @macro1 is there anything I can do to help you with this? What remains to be done? I can jum on finishing it up if you want (and if I'm able...)

**Comment by achillis1** [comment]
Any update on this issue? I really need it to be compatible with 1.10...

**Comment by nessalc** [comment]
I took @macro1's django110 branch and made a slight change to `middleware.py`, available [here](https://github.com/nessalc/django-simple-history/blob/django110/simple_history/middleware.py). It works for 1.10 and the current dev branch of Django, at least, but may not be backward (or forward) compatible from there.

**Comment by achillis1** [comment]
I'm still new to python django. @nessalc, could you please elaborate how to install your fix? I'll need it to be working on heroku too.

**Comment by nessalc** [comment]
@achillis1: If you run the following:

    git clone -b django110 https://github.com/nessalc/django-simple-history.git
    pip install django-simple-history/

it *should* work. I just needed a quick-and-dirty fix&mdash;no idea if it is compatible with heroku. I'm hoping @macro1 can wrap this up, because I'd prefer something that's less slap-dash than my approach.

**Comment by souliane** [comment]
Hi guys, thanks for this nice module that I'd like to use for a project based on Django 1.10. Do you have an estimation about when simple-history will be fully compatible with 1.10? Thanks!

**Comment by dalberto** [comment]
@nessalc How has your fix worked out? Have you encountered any issues in practice?

**Comment by nessalc** [comment]
@dalberto My fix has been functioning admirably in my particular application, and no, I haven't encountered any issues thus far. I don't claim to have tested it extensively--there are likely cases/situations that my fix doesn't work for--but at least for "simple" history, it's doing the job.

**Comment by icygithub** [comment]
File "/home/trusty/django/local/lib/python2.7/site-packages/simple_history/models.py", line 9, in <module>
    from django.db.models import loading
ImportError: cannot import name loading

Any help please?

**Comment by macro1** [comment]
1.10 support is now in master. I need to update the documentation, but a release will be coming soon. Thanks for your interest and patience everyone!

**Comment by KevinGrahamFoster** [comment]
Thanks @macro1 for all your great work. 👍
